#
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db # Sets service name
  labels:
    app: postgresql-db # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: postgresql-db
