version: '3'

services:
  registry:
    container_name: docker-registry
    restart: always
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_SECRET: "datacatalog"
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/registry.crt"
      REGISTRY_HTTP_TLS_KEY: "/certs/registry.key"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /Docker-Registry 
      REGISTRY_STORAGE_DELETE_ENABLED: true 
    volumes:
      - ./data:/Docker-Registry
      - ./certs:/certs